import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { format } from "prettier";

/**
 * Regenerates src/addresses.ts from the deployment artifacts the contracts
 * workspace writes to eque-contracts/deployments. Run after every deployment:
 *
 *   npm run sync:addresses
 */

const deploymentsDir = resolve(process.cwd(), "../eque-contracts/deployments");
const outputFile = resolve(process.cwd(), "src/addresses.ts");
const addressPattern = /^0x[0-9a-fA-F]{40}$/;

type Deployment = {
  chainId: number;
  deployedAt: string;
  deployer: string;
  tokens: Record<string, string>;
  feeds: Record<string, string>;
  strategies: Record<string, string>;
  vaults: Record<string, string>;
  router: string;
  factory: string;
  faucet: string;
};

function assertAddress(file: string, field: string, value: unknown): string {
  if (typeof value !== "string" || !addressPattern.test(value)) {
    throw new Error(`${file}: ${field} is not a valid address`);
  }
  return value;
}

function assertAddressMap(file: string, field: string, value: unknown): Record<string, string> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new Error(`${file}: ${field} is not an address map`);
  }
  const map: Record<string, string> = {};
  const entries = Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b));
  for (const [key, address] of entries) {
    map[key] = assertAddress(file, `${field}.${key}`, address);
  }
  return map;
}

function readDeployment(file: string): { network: string; deployment: Deployment } {
  const raw = JSON.parse(readFileSync(join(deploymentsDir, file), "utf8")) as Record<string, unknown>;
  if (typeof raw.network !== "string" || raw.network === "") {
    throw new Error(`${file}: missing network name`);
  }
  if (typeof raw.chainId !== "number") {
    throw new Error(`${file}: chainId must be a number`);
  }
  if (typeof raw.deployedAt !== "string") {
    throw new Error(`${file}: deployedAt must be a string`);
  }
  return {
    network: raw.network,
    deployment: {
      chainId: raw.chainId,
      deployedAt: raw.deployedAt,
      deployer: assertAddress(file, "deployer", raw.deployer),
      tokens: assertAddressMap(file, "tokens", raw.tokens),
      feeds: assertAddressMap(file, "feeds", raw.feeds),
      strategies: assertAddressMap(file, "strategies", raw.strategies),
      vaults: assertAddressMap(file, "vaults", raw.vaults),
      router: assertAddress(file, "router", raw.router),
      factory: assertAddress(file, "factory", raw.factory),
      faucet: assertAddress(file, "faucet", raw.faucet),
    },
  };
}

const files = readdirSync(deploymentsDir)
  .filter((file) => file.endsWith(".json"))
  .sort();

const byNetwork: Record<string, Deployment> = {};
for (const file of files) {
  const { network, deployment } = readDeployment(file);
  byNetwork[network] = deployment;
}

const deployments: Record<string, Deployment> = {};
const networks = Object.keys(byNetwork).sort();
for (const network of networks) {
  deployments[network] = byNetwork[network];
}

const source = [
  "// Generated by scripts/sync-addresses.ts from eque-contracts/deployments.",
  "// Do not edit by hand; run `npm run sync:addresses` after a deployment.",
  "",
  'import type { Address } from "viem";',
  "",
  "/** One chain's deployed Eque stack, as recorded by the deploy script. */",
  "export interface EqueDeployment {",
  "  chainId: number;",
  "  deployedAt: string;",
  "  deployer: Address;",
  "  tokens: Record<string, Address>;",
  "  feeds: Record<string, Address>;",
  "  strategies: Record<string, Address>;",
  "  vaults: Record<string, Address>;",
  "  router: Address;",
  "  factory: Address;",
  "  faucet: Address;",
  "}",
  "",
  "export const deployments: Record<string, EqueDeployment> = " + JSON.stringify(deployments, null, 2) + ";",
  "",
  "/** The recorded deployment for one chain. Throws when none exists yet. */",
  "export function getAddresses(chain: string): EqueDeployment {",
  "  const deployment = deployments[chain];",
  "  if (deployment === undefined) {",
  '    throw new Error("No Eque deployment recorded for " + chain + ". Run the deploy script for that network, then npm run sync:addresses.");',
  "  }",
  "  return deployment;",
  "}",
  "",
].join("\n");

const formatted = await format(source, { filepath: outputFile });
const previous = existsSync(outputFile) ? readFileSync(outputFile, "utf8") : "";
if (previous === formatted) {
  console.log(`src/addresses.ts unchanged (${networks.length} networks: ${networks.join(", ")})`);
} else {
  writeFileSync(outputFile, formatted);
  console.log(`src/addresses.ts written (${networks.length} networks: ${networks.join(", ")})`);
}